---
title: 'Coursera’s MMDS course Week 2B: Frequent Itemsets (Basic) - Quiz 2'
output: html_document
---

This is the solution of Coursera’s MMDS course Week 2B: Frequent Itemsets (Basic) - Quiz 2

# Question 1

Suppose we have transactions that satisfy the following assumptions: 
* s, the support threshold, is 10,000.
* There are one million items, which are represented by the integers 0,1,...,999999.
* There are N frequent items, that is, items that occur 10,000 times or more.
* There are one million pairs that occur 10,000 times or more.
* There are 2M pairs that occur exactly once. M of these pairs consist of two frequent items, the other M each have at least one nonfrequent item.
* No other pairs occur at all.
* Integers are always represented by 4 bytes.

Suppose we run the a-priori algorithm to find frequent pairs and can choose on the second pass between the triangular-matrix method for counting candidate pairs (a triangular array count[i][j] that holds an integer count for each pair of items (i, j) where i < j) and a hash table of item-item-count triples. Neglect in the first case the space needed to translate between original item numbers and numbers for the frequent items, and in the second case neglect the space needed for the hash table. Assume that item numbers and counts are always 4-byte integers. 

As a function of N and M, what is the minimum number of bytes of main memory needed to execute the a-priori algorithm on this data? Demonstrate that you have the correct formula by selecting, from the choices below, the triple consisting of values for N, M, and the (approximate, i.e., to within 10%) minumum number of bytes of main memory, S, needed for the a-priori algorithm to execute with this data.

Here's a hint. When considering the hash table for counting pairs of frequent items that actually occur in the data set, remember that you need 12 bytes per entry, 4 each to store the two item ID's and 4 to store the integer count. The number of 12-byte entries will be the number of pairs that occur in the data and have both items frequent.

## Solution

   S = 2*N^2
    

# Question 2

Imagine there are 100 baskets, numbered 1,2,...,100, and 100 items, similarly numbered. Item i is in basket j if and only if i divides j evenly. For example, basket 24 is the set of items {1,2,3,4,6,8,12,24}. Describe all the association rules that have 100% confidence. Which of the following rules has 100% confidence?

Consider, for example, basket 66, which is divisible by 1, 3, and 6 and therefore contains these items. However, 66 is not divisible by 12, and therefore 12 is not in basket 66. Thus, the presence of 1, 3, and 6 does not guarantee the presence of 12; i.e., the confidence of the rule is less than 100%


## Solution

Construction Rule
    1 -> {1}
    2 -> {1,2}
    3 -> {1,3}
    4 -> {1,2,4}
    5 -> {1,5}
    6 -> {1,2,3,6}
    7 -> {1,7}
    8 -> {1,2,4,8}
    
Only Item 1 is in every cart (e.g. {3,5} -> 1 is a valid solution).


# Question 3

Suppose ABC is a frequent itemset and BCDE is NOT a frequent itemset. Given this information, we can be sure that certain other itemsets are frequent and sure that certain itemsets are NOT frequent. Other itemsets may be either frequent or not. Which of the following is a correct classification of an itemset?

The converse of the a-priori principle says that if an itemset is not frequent, then its supersets are not frequent either. However, it does not imply any other sets are not frequent.

## Solution

ABC - frequent Itemset
BCDE - Non-frequent

* AB must be frequent
* D can be either frequent or non-frequent
* E can be either frequent or non-frequent
* DE must be non-frequent
* BCE can be either frequent or non-frequent
* BCDEF must be non-frequent
